import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const base=process.env.GAME_BASE||'http://127.0.0.1:4401/';
const sandbox={};vm.runInNewContext(fs.readFileSync('backstage-content-v1.js','utf8'),sandbox);
const data=structuredClone(sandbox.YGDRIA_BACKSTAGE_CONTENT);
const phase=structuredClone(data.realms[0].phases[0]);
phase.name='Santuário da Luz QA';phase.before='Abertura exclusiva da Luz';phase.after=[];phase.background='assets/bg/humanos/fase-02.jpg';
phase.music='assets/audio/Ygdria_Humanos_1_9.mp3';
phase.missions[0].music=phase.music;phase.missions.forEach(m=>{m.lines=[{speaker:'Narrador',heroId:'',text:'Missão exclusiva da Luz'}];m.enemies=['slimeCereja'];});
data.realms=data.realms.filter(r=>r.id==='humanos');
data.realms.push({id:'reino-da-luz',mapSlot:'luz',mapEnabled:true,name:'Reino da Luz',phases:[phase,{...structuredClone(phase),number:2,name:'Segunda fase da Luz'}]});
data.realms.push({id:'agua',mapSlot:'agua',mapEnabled:true,name:'Reino da Água',phases:[]});
const browser=await chromium.launch();
try{for(const width of [390,1440]){
 const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/backstage-content-v1.js*',route=>route.fulfill({contentType:'text/javascript',body:'window.YGDRIA_BACKSTAGE_CONTENT='+JSON.stringify(data)}));
 await page.goto(base+'play.html?qa=flow&seed=realm-test',{waitUntil:'networkidle'});
 await page.waitForFunction(()=>document.body.dataset.gameReady==='1');
 await page.evaluate(()=>{saveCardUnlocks(KINGDOMS.map(h=>h.id));localStorage.setItem('12r_tutorial_seen','true');localStorage.setItem('12r_tutorial','true');openMapScreen('world');});
 await page.getByRole('button',{name:'Reino da Luz',exact:true}).click();
 assert.match(await page.locator('#worldHead').innerText(),/Reino da Luz/);
 assert.match(await page.locator('#worldMap').innerText(),/Santuário da Luz QA/);
 assert.equal(await page.evaluate(()=>currentRealmId()),'reino-da-luz');
 await page.screenshot({path:`backstage/qa/map-light-${width}.png`});
 await page.evaluate(()=>{startWorldFase(0);beginGame(0);skipStory();});
 assert.equal(await page.evaluate(()=>currentStory()[0].before),'Abertura exclusiva da Luz');
 assert.equal(await page.evaluate(()=>stageMusicForWorldRun()),'editor-reino-da-luz-0-1');
 assert.equal(await page.evaluate(()=>enemies[0].etype),'slimeCereja');
 const humanBefore=await page.evaluate(()=>localStorage.getItem('12r_world_humanos'));
 await page.evaluate(()=>{worldRun.nivel=5;worldRun.storyMode=false;stageTransitioning=false;onStageCleared();});
 assert.equal(await page.evaluate(()=>worldProg('reino-da-luz').unlocked),1);
 assert.equal(await page.evaluate(()=>localStorage.getItem('12r_world_humanos')),humanBefore);
 assert.ok(await page.evaluate(()=>localStorage.getItem('12r_fase_time_reino-da-luz')));
 assert.ok(await page.evaluate(()=>isExportableSaveKey('12r_fase_time_reino-da-luz')));
 await page.evaluate(()=>validateImportedSaveEntry('12r_fase_time_reino-da-luz',localStorage.getItem('12r_fase_time_reino-da-luz')));
 await page.reload({waitUntil:'networkidle'});
 await page.evaluate(()=>openMapScreen('world'));
 await page.getByRole('button',{name:'Reino da Luz',exact:true}).click();
 assert.equal(await page.evaluate(()=>worldProg(currentRealmId()).unlocked),1);
 await page.evaluate(()=>{closeAllPanels();openMapScreen('world');});
 await page.getByRole('button',{name:'Reino da Água',exact:true}).click();
 assert.match(await page.locator('#worldMap').innerText(),/Campanha em preparação/);
 await page.evaluate(()=>{closeAllPanels();openMapScreen('world');});
 await page.getByRole('button',{name:'Reino dos Humanos',exact:true}).click();
 assert.equal(await page.evaluate(()=>currentWorld().fases.length),10);
 assert.equal(await page.evaluate(()=>currentStory()[0].missions[0][0].t),data.realms[0].phases[0].missions[0].lines[0].text);
 assert.deepEqual(errors,[]);await context.close();
}console.log('Novos reinos: mapa, narrativa, combate, música, progresso isolado, recarga e reino vazio aprovados em celular/desktop.');}finally{await browser.close();}
